spring:
  datasource:
    url: jdbc:mysql://80.211.205.197:3306/movieclub
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: movieClub
    password: N27xLvddt80zVCW
  liquibase:
    contexts: prod
  web:
    resources:
      static-locations: classpath:/static/,file:./uploads/
app:
  storage:
    location: ./uploads/