spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movieclub
    username: root
    password: 123qweQ!
  liquibase:
    contexts: prod
  web:
    resources:
      static-locations: classpath:/static/,file:./uploads
app:
  storage:
    location: ./uploads